name:                puriq
version:             0.1.0.0
github:              "erwinsaul/puriq"
license:             BSD-3-Clause
author:              "Erwin Saul Serrudo Condori"
maintainer:          "mackonkey@gmail.com"
copyright:           "2025 Erwin Saul Serrudo Condori"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Lenguaje de programación interpretado en español
category:            Programming Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/erwinsaul/puriq#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1 #para parsing
- containers >= 0.6 # Para Map, Set
- mtl >= 2.2 # Para mónadas
- text >=1.2 # Para el manejo de Strings
- bytestring >= 0.10 # Para manejo de archivos
- directory >= 1.3 # Para operaciones de archivos
- filepath >= 1.4 # Para rutas de archivos 
- haskeline >= 0.8 # Para REPL interactivo con tu historial


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  puriq-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - puriq

tests:
  puriq-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - puriq
    - hspec >= 2.10
    - hspec-discover >= 2.10
    - QuickCheck >= 2.14
    - hspec-core >= 2.10
    - HUnit >= 1.6
    - temporary >= 1.3
    - silently >= 1.2
